# docker-compose up --scale zap=2
# Waiting to see what happens with docker-compose-ui support in order to move to 3.8
#   https://github.com/francescou/docker-compose-ui/issues/120
#   https://github.com/francescou/docker-compose-ui/issues/110
version: "3.6"

networks:
  compose_pt-net:
    external: true

services:
  zap:
    image: owasp/zap2docker-stable:2.10.0
    networks:
      compose_pt-net:
    # Soft limit of 12 test sessions.
    ports:
    - "8080-8091:8080"
    # Todo: KC: create new api key on every test run.
    command: [
      "zap.sh",
      "-daemon",
      "-port",
      "8080",
      "-host",
      "0.0.0.0",
      "-config",
      "api.addrs.addr.regex=true",
      "-config",
      "api.addrs.addr.name=zap|localhost|127.0.0.1|172.25.0.*|appemissary_zap_(100|[1-9][0-9]?)",
      "-config",
      "api.key=${ZAP_API_KEY}"
    ]
    # Uncomment the bind mount to enable debug logs in Zap containers.
    volumes:
     - type: bind
       # Same variables found in contOrc IAC variables.tf for cloud environment.
       source: ${HOST_ZAP_LOG4J_PROPERTIES_PATH}
       target: ${ZAP_LOG4J_PROPERTIES_PATH_MOUNT_TARGET}

